# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from test_run1/advSpeed.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class advSpeed(genpy.Message):
  _md5sum = "c3f9e44ec1dd6d90b6e0e29b2b10ef31"
  _type = "test_run1/advSpeed"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint8 iskeepCurSpeed = 1
uint8 notkeepCurSpeed = 0


float64 upperSpeed
float64 bottomSpeed
uint8 keepCurSpeed
"""
  # Pseudo-constants
  iskeepCurSpeed = 1
  notkeepCurSpeed = 0

  __slots__ = ['upperSpeed','bottomSpeed','keepCurSpeed']
  _slot_types = ['float64','float64','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       upperSpeed,bottomSpeed,keepCurSpeed

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(advSpeed, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.upperSpeed is None:
        self.upperSpeed = 0.
      if self.bottomSpeed is None:
        self.bottomSpeed = 0.
      if self.keepCurSpeed is None:
        self.keepCurSpeed = 0
    else:
      self.upperSpeed = 0.
      self.bottomSpeed = 0.
      self.keepCurSpeed = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2dB().pack(_x.upperSpeed, _x.bottomSpeed, _x.keepCurSpeed))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 17
      (_x.upperSpeed, _x.bottomSpeed, _x.keepCurSpeed,) = _get_struct_2dB().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2dB().pack(_x.upperSpeed, _x.bottomSpeed, _x.keepCurSpeed))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 17
      (_x.upperSpeed, _x.bottomSpeed, _x.keepCurSpeed,) = _get_struct_2dB().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2dB = None
def _get_struct_2dB():
    global _struct_2dB
    if _struct_2dB is None:
        _struct_2dB = struct.Struct("<2dB")
    return _struct_2dB
