// Generated by gencpp from file test_run1/ObjectArray.msg
// DO NOT EDIT!


#ifndef TEST_RUN1_MESSAGE_OBJECTARRAY_H
#define TEST_RUN1_MESSAGE_OBJECTARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <test_run1/Object.h>

namespace test_run1
{
template <class ContainerAllocator>
struct ObjectArray_
{
  typedef ObjectArray_<ContainerAllocator> Type;

  ObjectArray_()
    : header()
    , size(0)
    , objects()  {
    }
  ObjectArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , size(0)
    , objects(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint16_t _size_type;
  _size_type size;

   typedef std::vector< ::test_run1::Object_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::test_run1::Object_<ContainerAllocator> >::other >  _objects_type;
  _objects_type objects;





  typedef boost::shared_ptr< ::test_run1::ObjectArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test_run1::ObjectArray_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectArray_

typedef ::test_run1::ObjectArray_<std::allocator<void> > ObjectArray;

typedef boost::shared_ptr< ::test_run1::ObjectArray > ObjectArrayPtr;
typedef boost::shared_ptr< ::test_run1::ObjectArray const> ObjectArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test_run1::ObjectArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test_run1::ObjectArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace test_run1

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'HasHeader': True, 'IsFixedSize': False, 'IsMessage': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'test_run1': ['/home/lz/test_demo/src/test_run1/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct HasHeader< ::test_run1::ObjectArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_run1::ObjectArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test_run1::ObjectArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test_run1::ObjectArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_run1::ObjectArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_run1::ObjectArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test_run1::ObjectArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "531e39cf33500dcf12cc20e992f43556";
  }

  static const char* value(const ::test_run1::ObjectArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x531e39cf33500dcfULL;
  static const uint64_t static_value2 = 0x12cc20e992f43556ULL;
};

template<class ContainerAllocator>
struct DataType< ::test_run1::ObjectArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test_run1/ObjectArray";
  }

  static const char* value(const ::test_run1::ObjectArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test_run1::ObjectArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
Header header\n\
\n\
uint16 size\n\
\n\
Object[] objects\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: test_run1/Object\n\
uint8 NEW_TARGET = 1\n\
uint8 UPDATE_TARGET = 3\n\
uint8 COASTED_TARGET = 4\n\
\n\
Header header\n\
\n\
float32 azimuth\n\
float32 distance\n\
\n\
float32 x\n\
float32 y\n\
\n\
float32 speed\n\
uint8 status\n\
uint8 id\n\
\n\
";
  }

  static const char* value(const ::test_run1::ObjectArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test_run1::ObjectArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.size);
      stream.next(m.objects);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test_run1::ObjectArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test_run1::ObjectArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "size: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.size);
    s << indent << "objects[]" << std::endl;
    for (size_t i = 0; i < v.objects.size(); ++i)
    {
      s << indent << "  objects[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::test_run1::Object_<ContainerAllocator> >::stream(s, indent + "    ", v.objects[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST_RUN1_MESSAGE_OBJECTARRAY_H
